version: "3.9"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .env
    depends_on: 
      - db
    volumes: 
      - .:/app
    network_mode: service:db
  db:
    image: postgres:latest
    container_name: pg_db
    environment: 
      POSTGRES_USER: meraki
      POSTGRES_PASSWORD: meraki2020*
      POSTGRESS_DB: meraki
    ports:
      - 5432:5432
      - 5000:5000
    volumes:
      - postgresdbvolume:/var/lib/postgresql/data 
volumes:
  postgresdbvolume: